services:

  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: wiki
      POSTGRES_PASSWORD: Z8lwab1Yt5KFxut
      POSTGRES_DB: outline
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio
    volumes:
      - ../data/minio_root:/minio_root:z
      - ../data/certs:/root/.minio/certs:z
    command: "minio server /minio_root"
    env_file: ../env/env.minio
    restart: always

  outline:
    image: outlinewiki/outline:latest
    environment:
      - DATABASE_URL=postgres://wiki:Z8lwab1Yt5KFxut@postgres:5432/outline
      - REDIS_URL=redis://redis:6379
    env_file:
      - ../env/env.outline
      - ../env/env.slack
    restart: always
    depends_on:
      - postgres
      - redis
      - minio
      
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ../data/nginx/:/etc/nginx/conf.d/:z
      - ../data/certs/:/etc/ssl/certs/:z
    restart: always
    depends_on:
      - outline
